Feature: Make a book catalog with new design JC-597
saritasa-nest/camp-js-2024-man-pham pull request #2
Opened 2024-07-04 04:51 UTC by manpham-saritasa

Make a book catalog page based on new design with HTML and CSS [JC-597](https://saritasa.atlassian.net/browse/JC-597)

NOTE: 
The reason why this PR only has one commit is because some of the previous commits were committed by my personal GitHub account. In order to fix the problem, I use git reset --soft and stash all of the commits into one commit to ensure that it is committed by the correct account.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa requested changes

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +        <section class="book-group">
In the lecture for russian team, I asked the guys to use grid for cards view. I understand that you didn't attend to lecture, so I'm asking you now.

The problem with flexbox, is that it's imposible to implement cards wrapping without empty space on the side (second image's width is slightly smaller): 
![image](https://github.com/saritasa-nest/camp-js-2024-man-pham/assets/98300391/e189f4ad-1096-4501-9aa1-6df20c47cdcc)
![Screenshot 2024-07-04 at 12 57 00](https://github.com/saritasa-nest/camp-js-2024-man-pham/assets/98300391/6c793d2e-6fe2-4f23-bfb9-62fdac981c72)

You can use this article:
https://ishadeed.com/article/css-grid-minmax/

TLDR: use `grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));`

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
>  }
It's good practice to place style blocks in media queries close to regular style blocks.

I mean this:
```css
.footer {...}
.footer__information {...}
@media only screen and (max-width: 767px) {
  .footer {...}
  .footer__information {...}
}
```

This way it's easier to grasp context and developer don't need to scroll back and forth.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/base.css
> +  box-sizing: border-box;
It's okay to use it now. But let's not change `box-sizing` for all elements in future tasks for Angular and React, because we don't usually do this in our projects.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +  max-width: 1280px;
I think it's good idea to extract it into variable, like you did for header and footer.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  object-fit: fill;
`fill` is distorting/stretching image, let's use `cover`.

```suggestion
  object-fit: cover;
```

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  position: absolute;
Why do you use it here? `position: absolute` should be used as less as possible, and I don't any reason to use in this case.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +.filter__form .search-bar {
BEM conceptually dissallows nested classes as selectors.

Your case should be rewritten this way to align with BEM methodology.
```css
.filter__seach {}
```

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +}
I think select and input should be **Block** (from BEM), and should be styled globally.

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +.filter__form .search-bar {
Basically, you always should use only 1 class by BEM methodology.

The only exception is state related styles, example:
```css
.partent:hover .parent__child {...}
```

2024-07-04 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +        <section class="book-group">
It also would work good on mobile screens

2024-07-04 07:43 UTC, artem-sotnichenko-saritasa commented
Also, please update styles for select and checkbox to match designs.

2024-07-04 08:58 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +  position: absolute;
Because I want the filter block to be fixed but still related to the parent which is containing it. Hence the mentioned implementation.

2024-07-04 09:03 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +  position: absolute;
My idea is to make the .filter to be "position:fixed" but still related to the parent element. Hence the mentioned implementation.

Here is the documentation: https://stackoverflow.com/a/11833892

2024-07-04 09:10 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Do you mean <input type="checkbox" /> element only ?

2024-07-04 09:11 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Do you mean the inputs with the type="checkbox" only?

2024-07-04 10:16 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.html
> +        <section class="book-group">
Thanks! The problem has been resolved

2024-07-04 10:17 UTC, manpham-saritasa commented on apps/vanilla/src/global/components.css
>  }
Thanks! The problem has been resolved

2024-07-04 10:18 UTC, manpham-saritasa commented on apps/vanilla/src/global/components.css
> +  max-width: 1280px;
Thanks! The problem has been resolved

2024-07-04 10:19 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +  object-fit: fill;
Thanks! The problem has been resolved

2024-07-04 10:20 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +.filter__form .search-bar {
Thanks! The problem has been resolved

2024-07-04 11:12 UTC, manpham-saritasa commented on apps/vanilla/src/global/base.css
> +  box-sizing: border-box;
So should I remove it or change its value?

2024-07-04 13:10 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/base.css
> +  box-sizing: border-box;
Keep it in vanilla.

2024-07-04 13:14 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  position: absolute;
Hmm, got it, it just don't needed in this particular case. You can just remove it, and `position fixed;` will still be working.

2024-07-04 14:05 UTC, manpham-saritasa commented on apps/vanilla/src/global/base.css
> +  box-sizing: border-box;
Thank you!

2024-07-04 14:17 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Thank you! The problem has been resolved

2024-07-04 14:18 UTC, manpham-saritasa commented on apps/vanilla/src/pages/index.css
> +  position: absolute;
Thanks a lot! The problem has been resolved

2024-07-05 10:43 UTC, maxineo approved these changes

2024-07-05 10:43 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  font-weight: var(--font-weight-bold);
These are not variables so lets move them to a separate file.

2024-07-06 04:49 UTC, manpham-saritasa commented on apps/vanilla/src/global/variables.css
> +  font-weight: var(--font-weight-bold);
How about I move them to another file called "styles.css" ?

2024-07-06 04:56 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  font-weight: var(--font-weight-bold);
I think `typography.css` will be fine.

2024-07-06 08:14 UTC, manpham-saritasa commented on apps/vanilla/src/global/variables.css
> +  font-weight: var(--font-weight-bold);
TYSM! The problem has been resolved

2024-07-07 12:34 UTC, EgorRyazanov approved these changes
Good job!

2024-07-08 01:36 UTC, maxineo approved these changes

2024-07-08 02:57 UTC, TienLuu-Saritasa approved these changes

2024-07-09 06:45 UTC, artem-sotnichenko-saritasa approved these changes

2024-07-09 06:45 UTC, artem-sotnichenko-saritasa commented on apps/react/src/api/index.ts
> +export const http: AxiosInstance = axios.create({
I don't think you need to write such detailed jsdoc for everything. Basically, you should explain only difficult, complex, or hacky code. 
And also, types are inherited from typescript, so there's no point to duplicate it in jsdoc

2024-07-09 06:45 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
> +const GenreCardComponent: FC<Props> = ({ genre }: Props) => (
`FC<Props>` is enough.

```suggestion
const GenreCardComponent: FC<Props> = ({ genre }) => (
```

2024-07-09 07:13 UTC, manpham-saritasa commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
> +const GenreCardComponent: FC<Props> = ({ genre }: Props) => (
Apparently, if I only use `FC<Props>`, and run the script `npm run react:lint`, I will have this error message: 

> Cannot read properties of undefined (reading 'typeAnnotation')
Occurred while linting .../camp-js-2024-man-pham/apps/react/src/features/genres/components/GenreCard/GenreCard.tsx:12
Rule: "jsdoc/require-param"
Pass --verbose to see the stacktrace.

So my VN team decided to put `{ genre }: Props` to prevent this error

2024-07-09 07:25 UTC, manpham-saritasa commented on apps/react/src/api/index.ts
> +export const http: AxiosInstance = axios.create({
Thank you! The problem has been resolved

2024-07-09 07:40 UTC, merged