Feature: Blackjack By Dice JC-623
saritasa-nest/camp-js-2024-man-pham pull request #4
Opened 2024-07-12 06:56 UTC by manpham-saritasa

Create a game called Blackjack By Dice to practice implementing the Observer design pattern.

Please go to this specific link [http://localhost:5173/blackjack/](http://localhost:5173/blackjack/) to view the work after running the project.

2024-07-12 17:36 UTC, LocTran-saritasa requested changes

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +}
You can change this class to `type`

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +	}
Constructor is inherited
```suggestion
```

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +		this.renderNewResult({ ...resultData });
Can we get rid of the spread operator?
```suggestion
		this.renderNewResult(resultData);
```

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/index.ts
> +	}
Why don't we call the `Dice.roll()` directly here but `turnGenerator.next()` -> `Dice.roll` ?

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/debugger.ts
> +		this.updateDicesList(playerDiceResult);
The variable name is Dice result, but the type is Turn result

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/index.ts
> +		this.turnGenerator = new TurnGenerator(this.playerCount);
```suggestion
	private readonly turnGenerator = new TurnGenerator(this.playerCount);

	public constructor() {
```

2024-07-12 17:36 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/index.ts
> +		});
Can we do this inside `createPlayers`?

2024-07-13 03:27 UTC, manpham-saritasa commented on apps/vanilla/src/pages/blackjack/script/index.ts
> +	}
I get your point, this may just be a misunderstanding because of the name of the function. My idea is that the TurnGenerator will be the controller of the game. When the app invokes `roll()` -> the turn generator will get the dice to roll to get the value and then notify the current player's index and the result of the dice to the players. Then the turn generator will move the index to the next player.

Maybe if I change to this, would it be clearer for you?
TurnGenerator: 
`public playTurn(): void {
		DiceGenerator.getInstance().roll();
	}
`
App:
`public playTurn(): void {
		this.turnGenerator.playTurn();
	}
`

2024-07-13 03:35 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/index.ts
> +	}
Thanks for the explanation. I got your idea. Your solution would stick to the class diagram more than what I suggested. Let's keep it as it is.

2024-07-13 04:44 UTC, LocTran-saritasa approved these changes

2024-07-13 04:44 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +};
We can add `readonly` our type. Please check other types as well
```suggestion
export type ResultData = {

	/** The array of dice values. */
	readonly dicesOrder: number[];

	/** The total value of all the dices. */
	readonly totalScore: number;
};
```

2024-07-13 04:44 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +	protected containerElement: HTMLElement | null = null;
```suggestion
	protected readonly containerElement: HTMLElement | null = null;
```

2024-07-13 04:44 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/player.ts
> +	public constructor(private playerIndex: number) {
Be consistent in class field definition with other places. You are mixing the common way with parameter properties

2024-07-13 05:33 UTC, manpham-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +	protected containerElement: HTMLElement | null = null;
This property will be assigned value by the inherit classes though...

2024-07-13 05:42 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +	protected containerElement: HTMLElement | null = null;
My bad, pls ignore this one

2024-07-16 10:38 UTC, EgorRyazanov approved these changes

2024-07-17 07:36 UTC, maxineo approved these changes

2024-07-17 07:36 UTC, maxineo commented on apps/vanilla/src/pages/blackjack/script/displayers.ts
> +					</h2>
```suggestion
				<div>
          <h2 class="displayer__heading">${name}
						<span id="${name}-score"></span>
					</h2>
```

2024-07-17 15:35 UTC, merged