Feature: Anime list management JC-655
saritasa-nest/camp-js-2024-man-pham pull request #7
Opened 2024-08-07 15:19 UTC by manpham-saritasa

Add auxiliary features to manage Anime list display:

- Add pagination to navigate of whole anime list;
- Add sorting by fields: title_eng, aired.start, status;
- Add searching feature
- Add filtering by type.

2024-08-13 04:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.html
> +		</table>
Skeletons 🔥

Can we reduce code duplication here?

2024-08-13 04:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/anime-query-params.service.ts
> +	 * Append provide query params and reset page number params to the URL.
```suggestion
	 * Append query params and reset page number params to the URL.
```

2024-08-13 04:13 UTC, timofei-maximov-saritasa commented on apps/angular/src/shared/components/table-cell-content/table-cell-content.component.html
> +<span *ngIf="isLoading; else contentTemplate" campSkeleton class="skeleton"></span>
Same with control flow

2024-08-13 04:13 UTC, timofei-maximov-saritasa commented on libs/core/models/anime-sort-fields.ts
> +
```suggestion
```

2024-08-19 13:37 UTC, timofei-maximov-saritasa approved these changes

2024-08-20 02:49 UTC, violetta-klintsova commented on apps/angular/src/app/features/home/anime-catalog/anime-catalog.component.ts
> +		// Add 'implements AfterViewInit' to the class.
Is it some sort of an unresolved TODO? 😅

2024-08-20 02:49 UTC, violetta-klintsova commented on libs/core/mappers/anime-filter-params.mapper.ts
> +};
It's better to mix too many things in one place, let's move this mapper into a separate file

2024-08-20 03:20 UTC, manpham-saritasa commented on apps/angular/src/app/features/home/anime-catalog/anime-catalog.component.ts
> +		// Add 'implements AfterViewInit' to the class.
Actually no, It's just the boilerplate when I use Angular snippets from VS Code))

2024-08-20 04:57 UTC, violetta-klintsova approved these changes

2024-08-26 05:20 UTC, pavel-romanov8 requested changes
I'm not sure why do we need this sidebar, it doesn't contain any functionality.

<img width="1703" alt="Screenshot 2567-08-26 at 11 50 29" src="https://github.com/user-attachments/assets/0c52e5fa-312b-478b-b5d4-8d4db0e05c74">

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-filter-form/anime-filter-form.component.ts
> +	@Input()
If any of those inputs are required we can makes the contract between parent and child component more strict
```suggestion
	@Input({ required: true })
```

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +	public pageSize = 0;
I see that we have global default values for page size. Can we use it here instead of `0`?

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +	protected sortEvent!: Sort;
Please try to avoid using the assertion operator as much as possible because you can't guarantee that it will always be `Sort`. In fact, we have 2 types of values that `sortEvent` can hold: `undefined` and `Sort`. It is `undefined` until the `ngOnInit` hooks run. Any code pies that tries to access this field before that gets `undefined`, not `Sort` object.

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +	public sortChange = new EventEmitter<AnimeFilterParams.Sort>();
```suggestion
	public readonly sortChange = new EventEmitter<AnimeFilterParams.Sort>();
```

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +				active: '',
If we have such an abstraction as `SortEventMapper` why do we move some of the event mapper logic here? It is responsibility of the sort mapper to properly handle such edge cases

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +		return function(_index: number, item: T): T[keyof T] {
From the function implementation code, I don't see any relation to `id` at all. We should either adjust the implementation to match the documentation or vice versa.

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/app/features/home/home.routes.ts
> +import { Routes } from '@angular/router';
```suggestion
import { Routes } from '@angular/router';
```

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/core/mappers/anime-filter-params.mapper.ts
> +	private typeMapper = inject(AnimeTypeMapper);
All those dependencies can be read-only

2024-08-26 05:20 UTC, pavel-romanov8 commented on apps/angular/src/shared/directives/skeleton/skeleton.directive.ts
> +	crypto.getRandomValues(array);
In this case, there is not much value in using the crypto module to generate random values because there is no need to make a prediction of skeleton size less possible. That's the only purpose of the crypto module. In fact, we're making our code slower using this function compared to a simple `Math.random`

2024-08-28 04:12 UTC, pavel-romanov8 commented on apps/angular/src/core/mappers/anime-sort-fields.mapper.ts
> +	public readonly MAP_SORT_COLUMNS_TO_SORT_FIELDS: Partial<Record<AnimeColumns, AnimeSortFields>> = {
Instead of exposing objects I would much rather expose functions. That way we take responsibility from accessing the right object from the end user and encapsulate it under a function. Compare to cases:
```typescript
export const MAP_SORT_FIELDS_TO_SORT_COLUMN: Record<AnimeSortFields, AnimeColumns> = {
		[AnimeSortFields.TitleEng]: AnimeColumns.TitleEng,
		[AnimeSortFields.StartDate]: AnimeColumns.StartDate,
		[AnimeSortFields.Status]: AnimeColumns.Status,
	};
	
	// later somewhere in the app
	
	MAP_SORT_FIELDS_TO_SORT_COLUMN[sortField];
```

VS

```typescript
const MAP_SORT_FIELDS_TO_SORT_COLUMN: Record<AnimeSortFields, AnimeColumns> = {
		[AnimeSortFields.TitleEng]: AnimeColumns.TitleEng,
		[AnimeSortFields.StartDate]: AnimeColumns.StartDate,
		[AnimeSortFields.Status]: AnimeColumns.Status,
	};
	
export function toSortField(column: AnimeSortColumn): AnimeSortFields {
  return MAP_SORT_FIELDS_TO_SORT_COLUMN[column];
}
```

It might look the same, but with function, we don't have to know how and where this mapping is coming from. We also don't have direct access to the object itself, which is a good thing because there is no way we can mutate it anywhere outside of the mapper.

2024-08-28 04:12 UTC, pavel-romanov8 commented on apps/angular/src/core/services/query-params.service.ts
> +	public appendParamsAndResetPageNumber(params: Record<string, any>, defaultPageNumber: number): void {
Why do we have some specific query parameters in a generic service? Such generic service as this one should only include low-level work with the router itself, like `append` method.

2024-08-28 04:12 UTC, pavel-romanov8 commented on apps/angular/src/core/services/query-params.service.ts
> +	public append(params: Record<string, any>): void {
I believe we can move type declaration into class generic so we don't have to repeat the code

2024-08-28 04:12 UTC, pavel-romanov8 commented on apps/angular/src/shared/components/table-cell-content/table-cell-content.component.ts
> +	public isLoading: Boolean | null = false;
`Boolean` is an object, please, don't use it for type definitions of a simple boolean values until you really need it

2024-08-28 04:12 UTC, pavel-romanov8 commented on libs/core/models/base-filter-params.ts
> +		pageNumber: number | null;
Should those be read-only?

2024-09-05 07:49 UTC, pavel-romanov8 approved these changes

2024-09-07 02:41 UTC, merged